### ISSUE TITLE
Verbal fluency should show a different cue letter each time

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#120]
I received 'a' as my cue letter two days in a row for the verbal fluency task.

According to the spec:

Cues to use = S, C, F, A, D, P 
One letter should be presented each of the 6 days, in a randomized order with no repeating of letters.

**Comment by noah10** [comment]
This should now be fixed. Please be sure to shift+reload before testing to make sure that you have the most recent version.

**Comment by maramather** [comment]
@nashiro who is assigned to analyze the verbal fluency data? Would that be me or Hyun Joo?

**Comment by nashiro** [comment]
Hyun Joo agreed to analyze the verbal fluency data.

**Comment by maramather** [comment]
Thanks @HyunjooY! Perhaps you could keep an eye out for whether this issue crops up at all in the data of those who completed this task since Noah fixed this issue.

**Comment by noah10** [comment]
We actually need to test this. It's challenging to determine whether it's likely to crop up in the data or not, as it depends on how many people had done how many iterations of verbal fluency before the fix went in (and after it went in).

**Comment by HyunjooY** [comment]
I will check the data and let you know.

**Comment by noah10** [comment]
I don't think checking the data will be enough, unfortunately. Even after I rolled out the fix it's possible that someone was still using the older version, so if we see the problem in the data we won't be able to conclude that it is not fixed. And of course if we don't see the problem in the data we can't conclude that it is fixed, since people could get only unused letters by random chance. I think you'll need to actually do verbal fluency five times and make sure you don't get any duplicate letters.

**Comment by HyunjooY** [comment]
Got it. I will test with a new account. Should this test be 6 days? Or is is possible to shorten to 3 days like 2 times a day for a test?

**Comment by noah10** [comment]
If you're using a new account, you could just go to https://dev.heartbeamstudy.org/daily-tasks/?tasks=verbal-fluency . You just need to enter one word and say you're done. Reload the page and you should get a new letter. Enter one word, say you're done, and repeat.

**Comment by HyunjooY** [comment]
Got it. I will try that way. Thank you!

**Comment by HyunjooY** [comment]
Sorry, Noah. I tried to setup  a new account with hyunjoo.yoo@gmail, but verifying the phone number was not working and stuck with that page, perhaps that is because I already used the same number. Is it okay to test with my old account (hyunjooy@usc.edu)? I am in the middle of trying daily tasks for 6 days. Or is there any way to set up a new account with the same phone number or any other suggestion?

**Comment by noah10** [comment]
Don't worry about phone number verification (though I would like to know how it failed - did you just not get the SMS?). The only thing that is for is so we can send you SMS reminders, which doesn't matter here. You should be able to do this testing with your new account.

**Comment by HyunjooY** [comment]
I did not get the SMS code and I only got email verification code. SO I submitted email verification code and then it says "There was a problem sending a verification code to your phone. Please try again."
And whenever I sign in, it shows the same message. 
And now I ignored the message and opened a new tab in chrome with task link, I could see the verbal fluency task instruction. I will continue to test.
I hope it is okay.

**Comment by HyunjooY** [comment]
I tried the verbal fluency task as you suggested.
And the letter was shown like this. 
F-S-P-F-P-S-A-P
I tried 8 times in a row to check to see what happens after 6 times.

**Comment by noah10** [comment]
OK - I'll look into it. I do see some errors in the log where you tried to use your usc.edu account but were denied access, which suggests that maybe  you were not logged in correctly, but I'm not sure if that was connected or not.

**Comment by HyunjooY** [comment]
This time I opened incognito mode and then log in as hyunjoo.yoo@gmail.com and now I could verify phone number (same number)...And then I tested it again. Still, there were repeated letters.
Letter: A-A-F-S-S-A

**Comment by noah10** [comment]
Well, I shot myself in the foot there. It turns out there was another bug that was specific to the single-task mode - if we had just tested it as part of the daily sets it would have been fine. Now it should be fine no matter whether you do it in single-task mode or as part of the daily sets (though you may need to shift+reload to get the latest version).

**Comment by noah10** [comment]
This is ready to be tested. The change only affected the single-task mode, so you can test it that way. (Or you can do it as part of daily sets if you really want to - obviously that should work, too.)

**Comment by HyunjooY** [comment]
I tested the verbal fluency in individual task mode using two accounts.
1) s-c-d-a-f-p
2) p-d-f-s-c-a
The task looks working correctly.
