### ISSUE TITLE
for reading the mind in the eyes test, please replace noun by adjective

### ISSUE THREAD

**Issue by mjDahl** [EmotionCognitionLab/pvs#150]
Completing the reading the mind in the eyes test for day 5, I notice that for one picture a noun was among the options whereas usually only adjectives are used (see attached screenshot) -- this could be adapted for consistency

![Screenshot 2021-11-19 at 12-36-52 Daily Tasks](https://user-images.githubusercontent.com/74646681/142623580-2845b2dd-859a-421a-b19c-5f0e59f906a7.png)

**Comment by maramather** [comment]
I initially thought that as we are using a widely used test and this error is in there we should just keep it. But it does seem like it would be reasonable to swap desirous for desire - and older adults notice things like that. So Noah or David, would you be able to make that change? Here is a potential definition: "having or characterized by desire (that is, a strong feeling of wanting to have something or wishing for something to happen)"

**Comment by noah10** [comment]
This is changed and ready for testing. Note that you may need to shift+reload to make sure that you have the latest version of the app. If you want to test it individually (rather than having to go through five days of daily tasks), you can do so here:

https://dev.heartbeamstudy.org/dailyTasks/?tasks=mind-in-eyes&setNum=5

**Comment by mjDahl** [comment]
Many thanks for the update, this worked on my end.
