### ISSUE TITLE
errors in which sets of stimuli to show (Pattern Separation Task)

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#159]
I realized that Set 2, 4, 6 for the Pattern Separation Task were shown on Day 2, 4, 6 in the pilot study which the team members completed recently. But could you show Set 1,2,3 on Day 2,4,6 at pre intervention and show Set 4,5,6 on Day 2,4,6 at post intervention? 

https://docs.google.com/document/d/1Fpgh3ecc2w6521SwkuyPWWRcfPbwtNmZdjiljqe5y_A/edit

https://docs.google.com/spreadsheets/d/1In7052RufUty29ta4QsR0YwnlyZCMAvsXk38ng8FCbU/edit#gid=0

**Comment by noah10** [comment]
I see. It's (clearly) confusing to have something labeled "Set 1" that's supposed to be shown as part of set 2. I think it would be best if you just edited the spreadsheet so that the stimuli you want shown as part of set 1 are labelled "Set 1", for set 2 "Set 2", etc. The post-intervention sets start at 7, so you would just label those "Set 7", "Set 8", etc. Just omit any sets that don't include a pattern separation task. Let me know when the spreadsheet is updated and I'll update the code to match.

**Comment by nashiro** [comment]
I edited the spreadsheet as suggested.

**Comment by noah10** [comment]
This should now be ready for testing. You can use something like this to control which set you're testing:

https://dev.heartbeamstudy.org/daily-tasks/?tasks=pattern-separation-learning&setNum=4

...and of course you can use tasks=pattern-separation-recall to test the recall phase. If everything looks as requested please close this issue.

**Comment by nashiro** [comment]
I tested all sets. Both learning and recall phases for Sets 2, 4, 6 look good. The stimuli seem to be correct (I did a spot check). The learning phases for for Sets 8, 10, 12 look good as well - the stimuli are correct.

But the recall phases for Sets 8, 10, 12 don't seem to be working. They show the learning phases, instead of recall. I used the following links. Are they the correct links?
https://dev.heartbeamstudy.org/daily-tasks/?tasks=pattern-separation-recall&setNum=8
https://dev.heartbeamstudy.org/daily-tasks/?tasks=pattern-separation-recall&setNum=10
https://dev.heartbeamstudy.org/daily-tasks/?tasks=pattern-separation-recall&setNum=12

Another thing I noticed was that for Sets 8, 10, 12, you can go though the whole learning and recall phases without full screen. It didn't give me a message to go full screen.

**Comment by noah10** [comment]
Sorry - because sets > 6 don't yet exist (we'll add them before the first participant is set to do the post baseline) you have to use a different URL format to test those:

https://dev.heartbeamstudy.org/daily-tasks/?tasks=pattern-separation&setNum=8&isRecall=true 

And sets > 6 won't ask you to go full-screen. Since you're interested in the stimuli, another way to test these would just be to look at https://github.com/EmotionCognitionLab/pvs/blob/main/baseline/client/pattern-separation/stimuli.json and see if the stimuli are correct.

**Comment by nashiro** [comment]
I see. I checked both links and all looks good. Thank you!
