### ISSUE TITLE
Creating a Summary Timestamp Document Across All Tasks Across All Sets 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#205]
We need a way to find out: 

1. How long it took a participant to complete each set?
2. How long it took a participant to complete each task in each set?
3. And also how long was the delay/waiting period for participants in Verbal Learning Recall? (I believe if the time b/w verbal learning & recall wasn't 20 min, they were given a screen as a countdown). 

I was able to manually calculate this with 4 people (for the pilot study) but I can see a lot of errors arising with 60 participants.

**Comment by noah10** [comment]
When you say "delay/waiting period" do you mean the time (if any) they spent watching the countdown timer or the time between finishing verbal-learning-learning and starting (not including any countdown timer) verbal-learning-recall?

**Comment by choipaul92** [comment]
Can we have both for Verbal Learning?

And for Pattern Separation Task is it possible if we can code: the time between Learning and Recall?

**Comment by noah10** [comment]
Sure, we can do both. Please open a separate issue for pattern separation. 

@Floozutter it feels like the JSON->CSV code is starting to get specialized for different tasks and include a lot of extra features beyond just converting JSON to CSV. We should go ahead and add it to this repo since it (unfortunately) is evolving into something that we're maintaining, rather than a starting point for researchers to do their own thing with.

**Comment by maramather** [comment]
I don't think getting a summary of how long each task/set took is high enough priority at this point to invest time doing it. But perhaps I'm just not aware of why we need this. @choipaul92 what do you think?

**Comment by nashiro** [comment]
Paul, Mara and I agreed that this is not high enough priority. So I'm closing this issue.
