### ISSUE TITLE
Paced Breathing: Adding A Timer/Countdown

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#220]
There should be a timer/countdown during Random Paced Breathing sessions.

**Comment by noah10** [comment]
I assume we want this for all paced breathing sessions, not just the random-paced ones, so I've changed the title.

**Comment by noah10** [comment]
We have a bit of a problem here: When the breathing pace is randomized we don't know exactly how long the entire sequence is going to take. This means that a 15 minute timer might finish a little before the actual paced breathing session ends. To handle this I'm going to just have the timer countdown in minutes, and then, rather than sitting there displaying "0 minutes remaining" while the pacer is still going, simply have it disappear once it hits 0. This will be inconsistent with the rest timer (which we'll keep in seconds, because there when the pulse sensor signal is lost the fact that the clock stops is an extra clue to the user that something has gone wrong), but oh well.

**Comment by choipaul92** [comment]
It seems like there is no way around that due to the randomization. I think the timer countdown in minutes should suffice since participants know that each session will take 15 min

**Comment by noah10** [comment]
This is in now, but after some unrelated changes it is only showing up intermittently. Still need to figure out why that is.

**Comment by noah10** [comment]
Well, now it seems to be showing up consistently, but I'm not sure why. 🤷 I'm going to mark it "needs testing" and we can see if it's consistent for everyone else, too.

**Comment by noah10** [comment]
Mara reports that on the first paced breathing session of the day the timer works well, but on the second it displays "1 minute remaining" at the start of the (15 minute long) session and then disappears shortly thereafter.

**Comment by noah10** [comment]
We have now made it so that users need to quit the app between the first and second sessions, which should solve the timer not appearing on the second session problem.

**Comment by choipaul92** [comment]
Just tested this out. And timer works on the second session after quitting the app. We should mention this to all users who want to continue on the next session right away.
