### ISSUE TITLE
Random Paced Breathing: Lumosity was not accessible 

### ISSUE THREAD

**Issue by choipaul92** [EmotionCognitionLab/pvs#222]
On certain days, Lumosity was not accessible, and random-paced breathing was only given.

**Comment by noah10** [comment]
What did the Lumosity screen display when it was not accessible? And which days did this happen to you?

**Comment by choipaul92** [comment]
This happened to me on 7/24 and I believe it was "continue onto the session" or it was straight to the random paced breathing

**Comment by noah10** [comment]
Approximately what time did it happen?

**Comment by choipaul92** [comment]
It happened at 9:09PM

**Comment by noah10** [comment]
Unfortunately I'm not seeing anything in the logs or in your saved data that would help explain this. The best explanation that I can think of is that Lumosity failed to load for some reason, leaving you with a screen that just said "After completing the Lumosity segment, please click here" and was otherwise blank. I'll try to add some code to catch a failure to load Lumosity and display an error/retry message if it happens.

**Comment by noah10** [comment]
Closing this because we haven't seen it again.
