### ISSUE TITLE
Prevent users from starting next stage on same day they finished previous one

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#227]
After finishing the Lumosity games and 5 minutes rest on Day 2, I opened the app again and it directed me to do random paced breathing (RPB).  But according to the schedule, RPB is supposed to start on Day 3.  Also, Day 3 should have started with Lumosity, not RPB?

**Comment by nashiro** [comment]
I've attached the instructions for this pilot study (in case it's helpful for Noah). 

[HeartBeam Pilot Study 8-Days Instructions_Paul_KNedits.docx](https://github.com/EmotionCognitionLab/pvs/files/9396254/HeartBeam.Pilot.Study.8-Days.Instructions_Paul_KNedits.docx)

**Comment by noah10** [comment]
The basic problem here is that we need some code to ensure that stage 3 starts on a different day than the one stage 2 ended on. Because no such code exists, you were able to (a) start stage 3 on day 2 and (b) stage 3 saw that you had already done lumosity that day (it didn't have any way to know that it was for stage 2), so it didn't have you do it again.

**Comment by noah10** [comment]
We have a similar problem with stage 1/stage 2. If they start stage 2 on the same day they finish stage 1 it won't have them do any rest breathing because it looks like they've already done it for the day - though it's really their stage 1 rest breathing.

**Comment by noah10** [comment]
Commit cebd8f88 is also related to this.

**Comment by noah10** [comment]
There have been no further reports of this. Closing.
