### ISSUE TITLE
checking for lumosity malingering

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#242]
Participants could press the button to say they have completed Lumosity when they haven’t. If daily breathing practice occurs more frequently than daily Lumosity practice, the application should alert the investigators to check what is going on. If a participant have a day when they did not do Lumosity but they did do at least some breathing, they should be flagged in the admin dashboard, and the admins should be able to remove the flag once it has been addressed.

**Comment by noah10** [comment]
UI suggestion: Add a "Lumos Status" (name could be better) column to the admin dashboard. If the column has a green check mark, all is well with the participant's Lumosity practice relative to their breathing practice. If the column has a red X admins can click on it to see which dates the participant has apparently failed to do Lumosity while still doing breathing practice. (Note that in order to do breathing practice they have to at least claim to have done Lumosity.) The admin can then call the participant to follow up and mark the date(s) as no longer relevant in the UI, causing it to switch from red X to green check mark. (At least until the participant malingers again in the future.)

**Comment by noah10** [comment]
We will have a column on the dashboard that indicates whether the participant has done all, some or almost none of the required tasks over the past five days. This will cover lumosity malingering because that indicator will draw on the actual lumosity reports, rather than the self reports. This means that a specific check for lumosity malingering is no longer needed.
