### ISSUE TITLE
Checking for breathing malingering

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#243]
So that we can monitor home practice performance and contact those who might just be wearing the ear sensor without doing the breathing, please add a column in the admin console that indicates if a participant's average performance score in the last 7 days is worse than their average across all days before the last 7 days.

**Comment by noah10** [comment]
This is probably going to make the dashboard quite slow, as it will have to download the entire breathing segments table, which will probably be tens of thousands of rows. What if we instead show how often a user has gotten a breathing bonus? To do that their median score for a given session has to be better than the average of all of their previous sessions. This is calculated in advance (once per day), so at worst we would only be fetching 2 rows/participant/day, rather than 6. (And that's assuming that participants get the bonus on every single breathing session, which probably won't be the case.)

**Comment by maramather** [comment]
Hmm, that will not provide us with a measure of getting worse. What if you compute:

(number of practice sessions in past 7 days - number of breathing bonuses) /
number of practice sessions in past 7 days

This should give the proportion of times that they perform worse than their average.

**Comment by noah10** [comment]
After further discussion it seems like we could probably use # of breathing bonuses / number of days since visit2 - 2 . The -2 is because your first day of breathing practice isn't eligible for breathing bonuses (-1 day) and the dashboard should always reflect yesterday (-1 more day) - we don't want to flag someone just because they haven't yet done today's breathing.

**Comment by maramather** [comment]
I've decided to do this manually 1x/month so am closing this issue.
