### ISSUE TITLE
potential extra day of stage 2

### ISSUE THREAD

**Issue by noah10** [EmotionCognitionLab/pvs#286]
Imagine that someone plays the Lumosity games necessary to complete stage 2 at 4:30PM PST on 11/28. Because this is 11/29 UTC, we won't know that they have completed Lumosity until around 1AM PST 11/30, when we get the Lumosity report that includes 11/29 (UTC) play data. If the person uses the home training app on 11/29, s/he will be given stage 2 tasks, meaning that s/he gets an extra day of stage 2 compared to someone who (for example) played the final Lumosity games needed to finish at 11AM PST on 11/28. Is this a problem?

**Comment by maramather** [comment]
It is not ideal, but as I see it, the only solution would be to trust them when they say they completed their practice on 11/28, which if they are wrong, would be a real problem (i.e., we MUST have at least the required number of gameplays and PREFER not to have more than the desired amount). So I’m thinking we’ll just have to live with some participants playing Lumosity an extra day in Stage 2.

From: noah10 ***@***.***>
Reply-To: EmotionCognitionLab/pvs ***@***.***>
Date: Friday, December 2, 2022 at 2:14 PM
To: EmotionCognitionLab/pvs ***@***.***>
Cc: Mara Mather ***@***.***>, Assign ***@***.***>
Subject: [EmotionCognitionLab/pvs] potential extra day of stage 2 (Issue #286)


Imagine that someone plays the Lumosity games necessary to complete stage 2 at 4:30PM PST on 11/28. Because this is 11/29 UTC, we won't know that they have completed Lumosity until around 1AM PST 11/30, when we get the Lumosity report that includes 11/29 (UTC) play data. If the person uses the home training app on 11/29, s/he will be given stage 2 tasks, meaning that s/he gets an extra day of stage 2 compared to someone who (for example) played the final Lumosity games needed to finish at 11AM PST on 11/28. Is this a problem?

**Comment by noah10** [comment]
OK - closing this, then.
