### ISSUE TITLE
Prompted to do 3rd paced breathing practice

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#316]
After completing the second 15-min paced breathing practice, I received a message saying to come back to do my second practice.  When I opened the app again and clicked on "continue to training", I was taken to a complete a 10-min paced breathing session.  This occurred on Day 2 of Stage 3.

**Comment by noah10** [comment]
For 12/22/2022, your emWave database shows a session from 09:19:27 to 09:33:26. Your HeartBEAM database, on the other hand, shows your first segment of the day ending at 9:28AM, suggesting that what you did from 9:19 to 9:23 didn't register. Did you have any sensor connection issues?

As of 10:26AM 12/22/2022, your last HeartBEAM database upload shows segments ending at the following times:

2022-12-22 09:28:27
2022-12-22 09:40:19
2022-12-22 09:45:29
2022-12-22 09:50:29

Your emwave database shows the following session IBIStart/End times:

2022-12-22 09:19:27|2022-12-22 09:33:26
2022-12-22 09:35:26|2022-12-22 09:50:28

All of this makes sense except for (a) you should have received warnings about sensor signal loss and (b) your statement that you did a 10-min paced breathing session. From this, it looks like you did 15 minutes, of which HB captured 5 minutes, and then went on to do another 15 minutes. I assume that you say it was 10 minutes because the timer said 10 minutes and that you didn't actually time it yourself?

**Comment by cho890** [comment]
When I first started paced breathing, I had sensor issues and had to stop after a few minutes.  I then restarted and did both 15-min sessions back to back.  

I didn't do the third 10-min session.  But because I was prompted to return to do another session after completing both 15-min sessions, I clicked on Daily Training to see what would happen.  I started the 10-min session and let it run for just a few seconds.  I thought it was odd because after completing both 15-min sessions yesterday, I got a message saying I was done with today's practice.

**Comment by noah10** [comment]
OK - I had misunderstood and thought you did the third session. Given that that's not the case this looks more-or-less normal, though obviously not ideal. It's expected that the connection between emWave and HB will be flaky sometimes - the bad part is that you didn't get sensor errors during your session from 9:19 - 9:33. I've added a little logging that will give us more info if this happens again, but I'm going to close this for now.
