### ISSUE TITLE
Payment dashboard not updating correctly

### ISSUE THREAD

**Issue by cho890** [EmotionCognitionLab/pvs#317]
I completed Day 2 of Stage 3 and have not received full payment.  I should have $2 for Breathing Practice for completing the previous day's practice.

**Comment by noah10** [comment]
Ugh - looks like my fix for #311 caused this bug. It happened because yesterday was the date that you transitioned from stage 2 to stage 3, so we treated you as being in stage 2. I think the right thing is to handle lumosity plays that happen before, but not on, your transition date as stage 2, while my fix did it as before **and** on.

**Comment by noah10** [comment]
This can be tested after 2AM PST 12/23/22.

**Comment by cho890** [comment]
Have completed 3 days of stage 3:
12/21 6:51AM
12/22 8:57AM
12/23 7:57AM

I show no payments for breathing practice.  I should have $2 for 12/21 session.  I should also have $2 for 12/22 session, but per our conversation yesterday, this won't be reflected due to HB error in logging training duration.  Since I completed 12/23 training, I should see $4 for breathing practice, correct?

**Comment by noah10** [comment]
I had forgotten to delete your old payments, which prevented your missing ones from being added. I've now done this and re-ran the earnings updates; please check again.

**Comment by cho890** [comment]
Payments now look accurate.
