### ISSUE TITLE
Flanker Task Infinite Practice

### ISSUE THREAD

**Issue by andyjkim628** [EmotionCognitionLab/pvs#34]
![flanker](https://user-images.githubusercontent.com/89949090/131758840-b6aed7f9-2ce3-4b77-bd5e-6d2a8c173226.png)

I cannot get out of the practice for the flanker task. I always get 2 wrong and it is an infinite loop. I have attached an image for what I see during the instructions. Perhaps there is something wrong with how things are displayed for me.

**Comment by noah10** [comment]
Hmmm... that is a really ugly display. What browser were you using? And if this was done full-screen, what are the dimensions of the monitor? (Btw, practice is supposed to be infinite if you don't get things right. It should not be hard to get them right, though.)

**Comment by noah10** [comment]
OK - can you try resizing your browser window and see if there's some size where it looks better? For me Chrome (92.0.4515.131) on OS X looks fine at 1920x1200 and smaller. (To a certain point - obviously it's possible to make it uselessly small.) Assuming you do get it looking better see if you still get the wrong answer all the time. Hopefully the only problem we have here is the display.

**Comment by andyjkim628** [comment]
I tried changing the resolution to 1920 x 1200 (I am using Windows 10). Interesting point is that the program prompted me that I am using a different monitor/computer. I said yes I am using a different monitor and it is permanent. However, it didn't solve the issue. It looks the same.

**Comment by noah10** [comment]
Hmmm... rather than changing your resolution, maybe try just going to https://dev.heartbeamstudy.org/flanker/index.html and play with the size of your browser window and see if there's any size where things look correct. I suspect that the answer is "no", but if it's "yes" then it tells us something about what we have to do to fix this. I'll also try this on a Windows emulator on my Mac and see what it looks like there. (And the stuff about the monitor/computer change warning is expected - we want people to do these at a consistent size if at all possible.)

**Comment by andyjkim628** [comment]
It actually works great with the above link (individual flanker task). I didn't have to change anything on my monitor and even worked when I did full-screen. Just to double-check, I went back to the daily tasks link and it still doesn't work for me there.

**Comment by noah10** [comment]
Thanks! That gave me a clue where to look, and I believe I've fixed it now. Can you please give it a try (as part of daily-tasks) and see if it works for you?

**Comment by andyjkim628** [comment]
It is fixed!
