### ISSUE TITLE
Change a few stimuli for the Pattern Separation Task

### ISSUE THREAD

**Issue by nashiro** [EmotionCognitionLab/pvs#341]
For Set 10 of the pattern separation task, please replace the following images with new ones. 

1. replace “nob_old_wood_cabinet1” with “nob_toy_shark1”  
2. replace “nob_old_wood_cabinet2” with “nob_toy_shark2”  
https://docs.google.com/spreadsheets/d/1In7052RufUty29ta4QsR0YwnlyZCMAvsXk38ng8FCbU/edit#gid=1702847630

Note: the reason for making these changes is because “nob_old_wood_cabinet1” and “nob_old_wood_cabinet2” were already used in Set 2 under different names (i.e., "nob_dresser1" and nob_dresser2").

**Comment by noah10** [comment]
JFYI, these images weren't quite identical. If you pull open each image in a new tab you'll see that one item in each pair is slightly larger than the other:

https://pvs-pictures.s3.us-west-2.amazonaws.com/pat/dresser2.jpg
https://pvs-pictures.s3.us-west-2.amazonaws.com/pat/old_wood_cabinet1.jpg

https://pvs-pictures.s3.us-west-2.amazonaws.com/pat/old_wood_cabinet2.jpg
https://pvs-pictures.s3.us-west-2.amazonaws.com/pat/dresser1.jpg

I imagine that doesn't matter - it's just unfortunate because it makes the job of automatically detecting this kind of error much harder.

The requested change has been made and is ready to be tested.

**Comment by nashiro** [comment]
Tested and all looks good - thank you!

Thanks for letting me know that the paired images are not the same size. It would be nice, but not critical, that they are the same size.
