### ISSUE TITLE
Dealing with missing Regime data after Day 4

### ISSUE THREAD

**Issue by maramather** [EmotionCognitionLab/pvs#366]
Currently, if a Random-Paced-Breathing participant does not complete all practice sessions in Days 1-4 (or there are issues saving data), there can be a regime (or multiple regimes) that have no saved data and so no confidence intervals and so is never selected for future practice sessions. 

To remedy this, before running the regime selection algorithm please implement the following step now detailed in the App Spec:
"First, check whether Regimes 2-7 (6 regimes) have confidence intervals from having been practiced on Days 1-4. If 4 or more of these are missing in the data, assign the participant to practice each regime 1x in random order. If 3 or fewer of these are missing, assign the participant to practice each missing regime 2x (if there were multiple missing regimes, randomize the order of these assigned regimes). This set of previously missing regimes should occur first in the assigned set. Any remaining slots should be filled by other regimes, randomly selected."

It is fine to implement this code for existing Random-Paced-Breathing participants but not necessary (so it will be unlikely to be implemented for them unless they get their app code updated for some other reason).

**Comment by noah10** [comment]
The specification for this has been updated:

> First, check whether the six original regimes have confidence intervals from having been practiced on Days 1-4. If 4 or more of these lack the minimum practice sessions to calculate a confidence interval (2) , assign the participant to practice each regime 1x in random order. If 3 or fewer of these lack CI’s, assign the participant to practice each lacking regime 2x. Any remaining slots should be filled by other regimes, randomly selected.

**Comment by noah10** [comment]
After discussion with Mara, we decided to change this up. We already include regimes that lack a confidence interval in the list of potential practice regimes. The trick is that we *don't* include regimes that lack any training data at all. This means that we will include any regime that has at least one training segment (which have no confidence interval - you need at least two to calculate that), but not ones that have 0. It's a much smaller change to simply include *all* regimes, whether they have training data or not, in the confidence interval calculation, so that's what we're going to do. The result will be that regimes with 0 or 1 training segments will automatically be included in the list of potential regimes for any given day, as will all with regimes with 2+ training segments whose confidence interval covers the target average coherence.

**Comment by noah10** [comment]
A production build (v2.0.6) with this change has been made available for future participants.
