### ISSUE TITLE
Screen changes color during last trial of Task Switching

### ISSUE THREAD

**Issue by ycazaherrera** [EmotionCognitionLab/pvs#75]
Anya and David have noted the following:

AV: "I was doing the tasks and in the task switching task, the last screen suddenly switches to creme instead of black which I don’t think is supposed to happen."

DW: "On the final question of the [task switching] task, the background suddenly switched from black to the light color"

**Comment by noah10** [comment]
This should now be fixed, with an important caveat: If the user is too slow in answering the final prompt, the "Answer faster next time" screen will be the default beige instead of black. (That screen doesn't appear at all if the user is fast enough.) And if you're doing this stand-alone (rather than as part of daily tasks) the screen that shows the data will also be beige, but that screen doesn't exist for regular users.

Alex, could you please have one or both of your RA's test this and could you close the issue if it's fixed?

**Comment by ycazaherrera** [comment]
Apologies. I forgot to close this out back in October.
